// Generated by gencpp from file img_seg/SegmentResponse.msg
// DO NOT EDIT!


#ifndef IMG_SEG_MESSAGE_SEGMENTRESPONSE_H
#define IMG_SEG_MESSAGE_SEGMENTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace img_seg
{
template <class ContainerAllocator>
struct SegmentResponse_
{
  typedef SegmentResponse_<ContainerAllocator> Type;

  SegmentResponse_()
    {
    }
  SegmentResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::img_seg::SegmentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::img_seg::SegmentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SegmentResponse_

typedef ::img_seg::SegmentResponse_<std::allocator<void> > SegmentResponse;

typedef boost::shared_ptr< ::img_seg::SegmentResponse > SegmentResponsePtr;
typedef boost::shared_ptr< ::img_seg::SegmentResponse const> SegmentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::img_seg::SegmentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::img_seg::SegmentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace img_seg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::img_seg::SegmentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::img_seg::SegmentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::img_seg::SegmentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::img_seg::SegmentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::img_seg::SegmentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::img_seg::SegmentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::img_seg::SegmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::img_seg::SegmentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::img_seg::SegmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "img_seg/SegmentResponse";
  }

  static const char* value(const ::img_seg::SegmentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::img_seg::SegmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::img_seg::SegmentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::img_seg::SegmentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SegmentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::img_seg::SegmentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::img_seg::SegmentResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IMG_SEG_MESSAGE_SEGMENTRESPONSE_H
